import { Propiedad } from "@/modules/propiedades/types/propiedad.type";
import { CreatePropiedad } from "../types/create-propiedad.types";

export const transformPropiedadToFormData = (propiedad: Propiedad): CreatePropiedad => {
	return {
		propiedad: {
			codigo: propiedad.codigo,
			calle: propiedad.calle,
			entre_calles: propiedad.entre_calles,
			numero: propiedad.numero,
			map_location: {
				type: "Point",
				coordinates: propiedad.map_location.coordinates as [number, number],
			},
			descripcion: propiedad.descripcion,
			tipo_propiedad: propiedad.tipo_propiedad.id,
			destacada: propiedad.destacada,
		},
		localidad_name: propiedad.localidad.nombre,
		ambientes: {
			altillo: propiedad.ambientes.altillo || false,
			balcon: propiedad.ambientes.balcon || false,
			baulera: propiedad.ambientes.baulera || false,
			biblioteca: propiedad.ambientes.biblioteca || false,
			cocina: propiedad.ambientes.cocina || false,
			comedor: propiedad.ambientes.comedor || false,
			comedor_diario: propiedad.ambientes.comedor_diario || false,
			dependencia: propiedad.ambientes.dependencia || false,
			escritorio: propiedad.ambientes.escritorio || false,
			galeria: propiedad.ambientes.galeria || false,
			hall: propiedad.ambientes.hall || false,
			jardin: propiedad.ambientes.jardin || false,
			lavadero: propiedad.ambientes.lavadero || false,
			living: propiedad.ambientes.living || false,
			living_comedor: propiedad.ambientes.living_comedor || false,
			oficina: propiedad.ambientes.oficina || false,
			patio: propiedad.ambientes.patio || false,
			sotano: propiedad.ambientes.sotano || false,
			suite: propiedad.ambientes.suite || false,
			terraza: propiedad.ambientes.terraza || false,
			toilette: propiedad.ambientes.toilette || false,
			vestidor: propiedad.ambientes.vestidor || false,
		},
		caracteristicas: {
			acceso_playa: propiedad.caracteristicas.acceso_playa || false,
			agua_caliente_central: propiedad.caracteristicas.agua_caliente_central || false,
			aire_acondicionado_individual:
				propiedad.caracteristicas.aire_acondicionado_individual || false,
			alarma: propiedad.caracteristicas.alarma || false,
			amoblado: propiedad.caracteristicas.amoblado || false,
			calefaccion_individual: propiedad.caracteristicas.calefaccion_individual || false,
			deck: propiedad.caracteristicas.deck || false,
			lavadero: propiedad.caracteristicas.lavadero || false,
			apto_credito: propiedad.caracteristicas.apto_credito || false,
			apto_mascotas: propiedad.caracteristicas.apto_mascotas || false,
			apto_profesional: propiedad.caracteristicas.apto_profesional || false,
			calefaccion: propiedad.caracteristicas.calefaccion || false,
			calefaccion_central: propiedad.caracteristicas.calefaccion_central || false,
			calefaccion_por_aire: propiedad.caracteristicas.calefaccion_por_aire || false,
			calefaccion_por_radiadores: propiedad.caracteristicas.calefaccion_por_radiadores || false,
			centro_de_deportes: propiedad.caracteristicas.centro_de_deportes || false,
			cochera_subterranea: propiedad.caracteristicas.cochera_subterranea || false,
			en_construccion: propiedad.caracteristicas.en_construccion || false,
			gimnasio: propiedad.caracteristicas.gimnasio || false,
			hidromasaje: propiedad.caracteristicas.hidromasaje || false,
			laundry: propiedad.caracteristicas.laundry || false,
			lote_interno: propiedad.caracteristicas.lote_interno || false,
			luminoso: propiedad.caracteristicas.luminoso || false,
			parrilla: propiedad.caracteristicas.parrilla || false,
			perimetral: propiedad.caracteristicas.perimetral || false,
			pileta: propiedad.caracteristicas.pileta || false,
			preinstalacion_aire_acondicionado:
				propiedad.caracteristicas.preinstalacion_aire_acondicionado || false,
			quincho: propiedad.caracteristicas.quincho || false,
			riego_automatico: propiedad.caracteristicas.riego_automatico || false,
			ruta: propiedad.caracteristicas.ruta || false,
			sala_de_juegos: propiedad.caracteristicas.sala_de_juegos || false,
			sauna: propiedad.caracteristicas.sauna || false,
			seguridad: propiedad.caracteristicas.seguridad || false,
			seguridad_24hs: propiedad.caracteristicas.seguridad_24hs || false,
			seguridad_dia: propiedad.caracteristicas.seguridad_dia || false,
			seguridad_porteria: propiedad.caracteristicas.seguridad_porteria || false,
			solarium: propiedad.caracteristicas.solarium || false,
			sum: propiedad.caracteristicas.sum || false,
		},
		detalles: {
			ambientes: propiedad.detalles.ambientes,
			superficie_lote: propiedad.detalles.superficie_lote,
			superficie_cubierta: propiedad.detalles.superficie_cubierta,
			superficie_total_construida: propiedad.detalles.superficie_total_construida,
			medida_frontal: propiedad.detalles.medida_frontal,
			medida_profundidad: propiedad.detalles.medida_profundidad,
			antiguedad: propiedad.detalles.antiguedad,
			dormitorios: propiedad.detalles.dormitorios,
			habitaciones: propiedad.detalles.habitaciones,
			banos: propiedad.detalles.banos,
			garage: propiedad.detalles.garage,
			pisos: propiedad.detalles.pisos,
			toilettes: propiedad.detalles.toilettes,
		},
		servicios: {
			agua_corriente: propiedad.servicios.agua_corriente || false,
			cloaca: propiedad.servicios.cloaca || false,
			electricidad: propiedad.servicios.electricidad || false,
			gas_natural: propiedad.servicios.gas_natural || false,
			internet: propiedad.servicios.internet || false,
			pavimento: propiedad.servicios.pavimento || false,
			telefono: propiedad.servicios.telefono || false,
			videocable: propiedad.servicios.videocable || false,
		},
		imagenes: propiedad.imagenes.map((img) => ({
			url: img.url,
			principal: img.principal,
		})),
		precios: propiedad.precios.map((precio) => ({
			estado_publicacion_id: precio.estado_publicacion.id,
			importe: precio.importe,
			divisa: precio.divisa,
		})),
	};
};
