import { CreatePropiedad } from "../types/create-propiedad.type";

export const CREATE_PROPIEDAD_DEFAULT_VALUES: CreatePropiedad = {
	propiedad: {
		codigo: Math.floor(Math.random() * (999999 - 100000 + 1)) + 100000,
		calle: "",
		entre_calles: "",
		numero: 0,
		map_location: {
			type: "Point",
			coordinates: [-58.3816, -34.6037],
		},
		descripcion: "",
		tipo_propiedad: 1,
		destacada: false,
	},
	localidad_name: "",
	ambientes: {
		altillo: false,
		balcon: false,
		baulera: false,
		biblioteca: false,
		cocina: false,
		comedor: false,
		comedor_diario: false,
		dependencia: false,
		escritorio: false,
		galeria: false,
		hall: false,
		jardin: false,
		lavadero: false,
		living: false,
		living_comedor: false,
		oficina: false,
		patio: false,
		sotano: false,
		suite: false,
		terraza: false,
		toilette: false,
		vestidor: false,
	},
	caracteristicas: {
		acceso_playa: false,
		agua_caliente_central: false,
		aire_acondicionado_individual: false,
		alarma: false,
		amoblado: false,
		calefaccion_individual: false,
		deck: false,
		lavadero: false,
		apto_credito: false,
		apto_mascotas: false,
		apto_profesional: false,
		calefaccion: false,
		calefaccion_central: false,
		calefaccion_por_aire: false,
		calefaccion_por_radiadores: false,
		centro_de_deportes: false,
		cochera_subterranea: false,
		en_construccion: false,
		gimnasio: false,
		hidromasaje: false,
		laundry: false,
		lote_interno: false,
		luminoso: false,
		parrilla: false,
		perimetral: false,
		pileta: false,
		preinstalacion_aire_acondicionado: false,
		quincho: false,
		riego_automatico: false,
		ruta: false,
		sala_de_juegos: false,
		sauna: false,
		seguridad: false,
		seguridad_24hs: false,
		seguridad_dia: false,
		seguridad_porteria: false,
		solarium: false,
		sum: false,
	},
	detalles: {
		ambientes: 0,
		superficie_lote: 0,
		superficie_cubierta: 0,
		superficie_total_construida: 0,
		medida_frontal: 0,
		medida_profundidad: 0,
		antiguedad: "",
		dormitorios: 0,
		habitaciones: 0,
		banos: 0,
		garage: "",
		pisos: 0,
		toilettes: 0,
	},
	servicios: {
		agua_corriente: false,
		cloaca: false,
		electricidad: false,
		gas_natural: false,
		internet: false,
		pavimento: false,
		telefono: false,
		videocable: false,
	},
	imagenes: [],
	precios: [],
};
